#!/bin/bash
apt -y install nano zip python cowsay python2 wget php git zsh
pip2 install beautifulsoup4 
pip2 install termcolor
pip2 install argparse
pip2 install request
pip2 install pysocks
pkg install mpv
pkg instalk libcurl
pip install mps_youtube
pip install youtube_dl
cowsay now run with python2
cowsay python2 stark.py
