#!/bin/bash
apt -y install nano zip python cowsay python2 wget php git zsh
pip2 install beautifulsoup4 
pip2 install termcolor
pip2 install argparse
pip2 install request
pip2 install pysocks
cowsay now run with python2
cowsay python2 stark.py
